[settings.default_install]
windows = "C:\\!PORTABLES\\!BIN"
linux = "~/.bin"

[tools.fd]
repo = "sharkdp/fd"
description = "A simple, fast and user-friendly alternative to 'find'"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "10.4.2"

[tools.fd.platforms.windows]
asset_pattern = "fd-*-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "fd-*-x86_64-pc-windows-msvc/fd.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\fd.EXE"

[tools.fd.platforms.linux]
asset_pattern = "fd-*-x86_64-unknown-linux-musl.tar.gz"
files_in_archive = [
    "fd-*-x86_64-unknown-linux-musl/fd",
]
install_path = "~/.bin/fd"

[tools.rip]
repo = "MilesCranmer/rip2"
description = "A safe and ergonomic alternative to rm"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "0.9.6"

[tools.rip.platforms.windows]
asset_pattern = "rip-Windows-x86_64.zip"
files_in_archive = [
    "rip.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\rip.EXE"

[tools.rip.platforms.linux]
asset_pattern = "rip-Linux-x86_64-musl.tar.gz"
files_in_archive = [
    "rip",
]
install_path = "~/.bin/rip"

[tools.pmux]
repo = "psmux/psmux"
description = "Tmux on Windows Powershell - tmux for PowerShell, Windows Terminal, cmd.exe. Includes psmux, pmux, and tmux commands. This is native Powershell Tmux designed for Windows in Rust 🦀"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "3.3.5"

[tools.pmux.platforms.windows]
asset_pattern = "psmux-*-windows-x64.zip"
files_in_archive = [
    "pmux.exe",
    "psmux.exe",
    "tmux.exe",
]
binary_names = [
    "pmux.exe",
    "psmux.exe",
    "tmux.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\pmux.exe"

[tools.arch]
repo = "uutils/coreutils"
description = "Cross-platform Rust rewrite of the GNU coreutils"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "0.9.0"

[tools.arch.platforms.windows]
asset_pattern = "coreutils-*-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "coreutils-*-x86_64-pc-windows-msvc/arch.exe",
    "coreutils-*-x86_64-pc-windows-msvc/b2sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/base32.exe",
    "coreutils-*-x86_64-pc-windows-msvc/base64.exe",
    "coreutils-*-x86_64-pc-windows-msvc/basename.exe",
    "coreutils-*-x86_64-pc-windows-msvc/basenc.exe",
    "coreutils-*-x86_64-pc-windows-msvc/cat.exe",
    "coreutils-*-x86_64-pc-windows-msvc/cksum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/comm.exe",
    "coreutils-*-x86_64-pc-windows-msvc/cp.exe",
    "coreutils-*-x86_64-pc-windows-msvc/csplit.exe",
    "coreutils-*-x86_64-pc-windows-msvc/cut.exe",
    "coreutils-*-x86_64-pc-windows-msvc/date.exe",
    "coreutils-*-x86_64-pc-windows-msvc/dd.exe",
    "coreutils-*-x86_64-pc-windows-msvc/df.exe",
    "coreutils-*-x86_64-pc-windows-msvc/dir.exe",
    "coreutils-*-x86_64-pc-windows-msvc/dircolors.exe",
    "coreutils-*-x86_64-pc-windows-msvc/dirname.exe",
    "coreutils-*-x86_64-pc-windows-msvc/du.exe",
    "coreutils-*-x86_64-pc-windows-msvc/echo.exe",
    "coreutils-*-x86_64-pc-windows-msvc/env.exe",
    "coreutils-*-x86_64-pc-windows-msvc/expand.exe",
    "coreutils-*-x86_64-pc-windows-msvc/expr.exe",
    "coreutils-*-x86_64-pc-windows-msvc/factor.exe",
    "coreutils-*-x86_64-pc-windows-msvc/false.exe",
    "coreutils-*-x86_64-pc-windows-msvc/fmt.exe",
    "coreutils-*-x86_64-pc-windows-msvc/fold.exe",
    "coreutils-*-x86_64-pc-windows-msvc/head.exe",
    "coreutils-*-x86_64-pc-windows-msvc/hostname.exe",
    "coreutils-*-x86_64-pc-windows-msvc/join.exe",
    "coreutils-*-x86_64-pc-windows-msvc/link.exe",
    "coreutils-*-x86_64-pc-windows-msvc/ln.exe",
    "coreutils-*-x86_64-pc-windows-msvc/ls.exe",
    "coreutils-*-x86_64-pc-windows-msvc/md5sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/mkdir.exe",
    "coreutils-*-x86_64-pc-windows-msvc/mktemp.exe",
    "coreutils-*-x86_64-pc-windows-msvc/more.exe",
    "coreutils-*-x86_64-pc-windows-msvc/mv.exe",
    "coreutils-*-x86_64-pc-windows-msvc/nl.exe",
    "coreutils-*-x86_64-pc-windows-msvc/nproc.exe",
    "coreutils-*-x86_64-pc-windows-msvc/numfmt.exe",
    "coreutils-*-x86_64-pc-windows-msvc/od.exe",
    "coreutils-*-x86_64-pc-windows-msvc/paste.exe",
    "coreutils-*-x86_64-pc-windows-msvc/pathchk.exe",
    "coreutils-*-x86_64-pc-windows-msvc/pr.exe",
    "coreutils-*-x86_64-pc-windows-msvc/printenv.exe",
    "coreutils-*-x86_64-pc-windows-msvc/printf.exe",
    "coreutils-*-x86_64-pc-windows-msvc/ptx.exe",
    "coreutils-*-x86_64-pc-windows-msvc/pwd.exe",
    "coreutils-*-x86_64-pc-windows-msvc/readlink.exe",
    "coreutils-*-x86_64-pc-windows-msvc/realpath.exe",
    "coreutils-*-x86_64-pc-windows-msvc/rm.exe",
    "coreutils-*-x86_64-pc-windows-msvc/rmdir.exe",
    "coreutils-*-x86_64-pc-windows-msvc/seq.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sha1sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sha224sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sha256sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sha384sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sha512sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/shred.exe",
    "coreutils-*-x86_64-pc-windows-msvc/shuf.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sleep.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sort.exe",
    "coreutils-*-x86_64-pc-windows-msvc/split.exe",
    "coreutils-*-x86_64-pc-windows-msvc/stdbuf.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sum.exe",
    "coreutils-*-x86_64-pc-windows-msvc/sync.exe",
    "coreutils-*-x86_64-pc-windows-msvc/tac.exe",
    "coreutils-*-x86_64-pc-windows-msvc/tail.exe",
    "coreutils-*-x86_64-pc-windows-msvc/tee.exe",
    "coreutils-*-x86_64-pc-windows-msvc/test.exe",
    "coreutils-*-x86_64-pc-windows-msvc/touch.exe",
    "coreutils-*-x86_64-pc-windows-msvc/tr.exe",
    "coreutils-*-x86_64-pc-windows-msvc/true.exe",
    "coreutils-*-x86_64-pc-windows-msvc/truncate.exe",
    "coreutils-*-x86_64-pc-windows-msvc/tsort.exe",
    "coreutils-*-x86_64-pc-windows-msvc/tty.exe",
    "coreutils-*-x86_64-pc-windows-msvc/uname.exe",
    "coreutils-*-x86_64-pc-windows-msvc/unexpand.exe",
    "coreutils-*-x86_64-pc-windows-msvc/uniq.exe",
    "coreutils-*-x86_64-pc-windows-msvc/unlink.exe",
    "coreutils-*-x86_64-pc-windows-msvc/vdir.exe",
    "coreutils-*-x86_64-pc-windows-msvc/wc.exe",
    "coreutils-*-x86_64-pc-windows-msvc/whoami.exe",
    "coreutils-*-x86_64-pc-windows-msvc/yes.exe",
]
binary_names = [
    "arch.exe",
    "b2sum.exe",
    "base32.exe",
    "base64.exe",
    "basename.exe",
    "basenc.exe",
    "cat.exe",
    "cksum.exe",
    "comm.exe",
    "cp.exe",
    "csplit.exe",
    "cut.exe",
    "date.exe",
    "dd.exe",
    "df.exe",
    "dir.exe",
    "dircolors.exe",
    "dirname.exe",
    "du.exe",
    "echo.exe",
    "env.exe",
    "expand.exe",
    "expr.exe",
    "factor.exe",
    "false.exe",
    "fmt.exe",
    "fold.exe",
    "head.exe",
    "hostname.exe",
    "join.exe",
    "link.exe",
    "ln.exe",
    "ls.exe",
    "md5sum.exe",
    "mkdir.exe",
    "mktemp.exe",
    "more.exe",
    "mv.exe",
    "nl.exe",
    "nproc.exe",
    "numfmt.exe",
    "od.exe",
    "paste.exe",
    "pathchk.exe",
    "pr.exe",
    "printenv.exe",
    "printf.exe",
    "ptx.exe",
    "pwd.exe",
    "readlink.exe",
    "realpath.exe",
    "rm.exe",
    "rmdir.exe",
    "seq.exe",
    "sha1sum.exe",
    "sha224sum.exe",
    "sha256sum.exe",
    "sha384sum.exe",
    "sha512sum.exe",
    "shred.exe",
    "shuf.exe",
    "sleep.exe",
    "sort.exe",
    "split.exe",
    "stdbuf.exe",
    "sum.exe",
    "sync.exe",
    "tac.exe",
    "tail.exe",
    "tee.exe",
    "test.exe",
    "touch.exe",
    "tr.exe",
    "true.exe",
    "truncate.exe",
    "tsort.exe",
    "tty.exe",
    "uname.exe",
    "unexpand.exe",
    "uniq.exe",
    "unlink.exe",
    "vdir.exe",
    "wc.exe",
    "whoami.exe",
    "yes.exe",
]
install_path = "C:\\!PORTABLES\\!GNU\\arch.exe"

[tools.rtk]
repo = "rtk-ai/rtk"
description = "CLI proxy that reduces LLM token consumption by 60-90% on common dev commands. Single Rust binary, zero dependencies"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "0.42.3"

[tools.rtk.platforms.windows]
asset_pattern = "rtk-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "rtk.exe",
]
binary_names = [
    "rtk.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\rtk.exe"

[tools.rtk.platforms.linux]
asset_pattern = "rtk-x86_64-unknown-linux-musl.tar.gz"
files_in_archive = [
    "rtk",
]
binary_names = [
    "rtk",
]
install_path = "~/.bin/rtk"

[tools.websocat]
repo = "vi/websocat"
description = "Command-line client for WebSockets, like netcat (or curl) for ws:// with advanced socat-like functions"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "1.14.1"

[tools.websocat.platforms.windows]
asset_pattern = "websocat.x86_64-pc-windows-gnu.exe"
binary_names = [
    "websocat.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\websocat.exe"

[tools.websocat.platforms.linux]
asset_pattern = "websocat.x86_64-unknown-linux-musl"
binary_names = [
    "websocat",
]
install_path = "~/.bin/websocat"

[tools.rg]
repo = "BurntSushi/ripgrep"
description = "ripgrep recursively searches directories for a regex pattern while respecting your gitignore"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "15.1.0"

[tools.rg.platforms.windows]
asset_pattern = "ripgrep-*-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "ripgrep-*-x86_64-pc-windows-msvc/rg.exe",
]
binary_names = [
    "rg.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\rg.exe"

[tools.rg.platforms.linux]
asset_pattern = "ripgrep-*-x86_64-unknown-linux-musl.tar.gz"
files_in_archive = [
    "ripgrep-*-x86_64-unknown-linux-musl/rg",
]
binary_names = [
    "rg",
]
install_path = "~/.bin/rg"

[tools.bat]
repo = "sharkdp/bat"
description = "A cat(1) clone with wings."
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "0.26.1"

[tools.bat.platforms.windows]
asset_pattern = "bat-*-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "bat-*-x86_64-pc-windows-msvc/bat.exe",
]
binary_names = [
    "bat.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\bat.exe"

[tools.bat.platforms.linux]
asset_pattern = "bat-*-x86_64-unknown-linux-musl.tar.gz"
files_in_archive = [
    "bat-*-x86_64-unknown-linux-musl/bat",
]
binary_names = [
    "bat",
]
install_path = "~/.bin/bat"

[tools.yazi]
repo = "sxyazi/yazi"
description = "💥 Blazing fast terminal file manager written in Rust, based on async I/O."
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "26.5.6"

[tools.yazi.platforms.windows]
asset_pattern = "yazi-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "yazi-x86_64-pc-windows-msvc/yazi.exe",
    "yazi-x86_64-pc-windows-msvc/ya.exe",
]
binary_names = [
    "yazi.exe",
    "ya.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\yazi.exe"

[tools.yazi.platforms.linux]
asset_pattern = "yazi-x86_64-unknown-linux-musl.zip"
files_in_archive = [
    "yazi-x86_64-unknown-linux-musl/yazi",
    "yazi-x86_64-unknown-linux-musl/ya",
]
binary_names = [
    "yazi",
    "ya",
]
install_path = "~/.bin/yazi"

[tools.code2prompt]
repo = "mufeedvh/code2prompt"
description = "A CLI tool to convert your codebase into a single LLM prompt with source tree, prompt templating, and token counting."
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "4.2.0"

[tools.code2prompt.platforms.windows]
asset_pattern = "code2prompt-x86_64-pc-windows-msvc.exe"
binary_names = [
    "code2prompt.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\code2prompt.exe"

[tools.code2prompt.platforms.linux]
asset_pattern = "code2prompt-x86_64-unknown-linux-gnu"
binary_names = [
    "code2prompt",
]
install_path = "~/.bin/code2prompt"

[tools.sd]
repo = "chmln/sd"
description = "Intuitive find & replace CLI (sed alternative)"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "1.0.0"

[tools.sd.platforms.windows]
asset_pattern = "sd-*-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "sd-*-x86_64-pc-windows-msvc/sd.exe",
]
binary_names = [
    "sd.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\sd.exe"

[tools.watchexec]
repo = "watchexec/watchexec"
description = "Executes commands in response to file modifications"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "2.5.1"

[tools.watchexec.platforms.windows]
asset_pattern = "watchexec-*-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "watchexec-*-x86_64-pc-windows-msvc/watchexec.exe",
]
binary_names = [
    "watchexec.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\watchexec.exe"

[tools.watchexec.platforms.linux]
asset_pattern = "watchexec-*-x86_64-unknown-linux-musl.tar.xz"
files_in_archive = [
    "watchexec-*-x86_64-unknown-linux-musl/watchexec",
]
binary_names = [
    "watchexec",
]
install_path = "~/.bin/watchexec"

[tools.htmlq]
repo = "mgdm/htmlq"
description = "Like jq, but for HTML."
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "0.4.0"

[tools.htmlq.platforms.windows]
asset_pattern = "htmlq-x86_64-windows.zip"
files_in_archive = [
    "htmlq.exe",
]
binary_names = [
    "htmlq.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\htmlq.exe"

[tools.htmlq.platforms.linux]
asset_pattern = "htmlq-x86_64-linux.tar.gz"
files_in_archive = [
    "htmlq",
]
binary_names = [
    "htmlq",
]
install_path = "~/.bin/htmlq"

[tools.mdcat]
repo = "swsnr/mdcat"
description = "cat for markdown"
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "2.7.1"

[tools.mdcat.platforms.windows]
asset_pattern = "*-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "mdcat.exe",
]
binary_names = [
    "mdcat.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\mdcat.exe"

[tools.mdcat.platforms.linux]
asset_pattern = "*-x86_64-unknown-linux-gnu.tar.gz"
files_in_archive = [
    "*-x86_64-unknown-linux-gnu/mdcat",
]
binary_names = [
    "mdcat",
]
install_path = "~/.bin/mdcat"

[tools.ruff]
repo = "astral-sh/ruff"
description = "An extremely fast Python linter and code formatter, written in Rust."
version_args = [
    "--version",
]
version_regex = "(\\d+\\.\\d+\\.\\d+(?:[.\\-][a-zA-Z0-9]+)*)"
installed_version = "0.15.16"

[tools.ruff.platforms.windows]
asset_pattern = "ruff-x86_64-pc-windows-msvc.zip"
files_in_archive = [
    "ruff.exe",
]
binary_names = [
    "ruff.exe",
]
install_path = "C:\\!PORTABLES\\!BIN\\ruff.exe"

[tools.ruff.platforms.linux]
asset_pattern = "ruff-x86_64-unknown-linux-musl.tar.gz"
files_in_archive = [
    "ruff-x86_64-unknown-linux-musl/ruff",
]
binary_names = [
    "ruff",
]
install_path = "~/.bin/ruff"
